title: "Aneka Shop"
email: anekashop2024@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Aneka Shop
paginate: 30
disqus: 'anekashop'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  anekashop:
    name: Aneka Shop
    display_name: Aneka Shop
    avatar: 'assets/images/anekaproduk.png'
    email: anekashop2024@gmail.com
    web: https://anekashop.github.io/
    twitter: 
    description: "Menjual semua produk terbaik dan beragam jenis."

# Social
social:
  instagram: https://www.instagram.com/anekashop/
  facebook: https://www.facebook.com/anekashop
  twitter: https://twitter.com/anekashop

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
